# Generated by Django 5.2.9 on 2025-12-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя водителя")),
                (
                    "car_model",
                    models.CharField(max_length=50, verbose_name="Модель автомобиля"),
                ),
                (
                    "car_number",
                    models.CharField(max_length=15, verbose_name="Номер автомобиля"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("rating", models.FloatField(default=5.0, verbose_name="Рейтинг")),
                (
                    "experience",
                    models.IntegerField(default=1, verbose_name="Стаж (лет)"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступен"),
                ),
                (
                    "photo",
                    models.CharField(
                        default="🚗", max_length=200, verbose_name="Фото (эмодзи)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Водитель",
                "verbose_name_plural": "Водители",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Имя клиента"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Телефон клиента"),
                ),
                ("pickup_address", models.TextField(verbose_name="Адрес подачи")),
                ("destination", models.TextField(verbose_name="Адрес назначения")),
                (
                    "order_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время заказа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("accepted", "Принят"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="B0J_app.driver",
                        verbose_name="Водитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-order_time"],
            },
        ),
    ]
