# Generated by Django 5.2.9 on 2025-12-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("B0J_app", "0002_order_distance_order_estimated_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("economy", "🚗 Эконом"),
                            ("comfort", "🚙 Комфорт"),
                            ("business", "🏎️ Бизнес"),
                            ("premium", "⭐ Премиум"),
                            ("cargo", "🚚 Грузовой"),
                            ("family", "👨\u200d👩\u200d👧\u200d👦 С детьми"),
                        ],
                        max_length=20,
                        verbose_name="Тип тарифа",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Базовая цена (₽)"
                    ),
                ),
                (
                    "price_per_km",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Цена за км (₽)"
                    ),
                ),
                (
                    "price_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Цена за минуту (₽)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🚗", max_length=10, verbose_name="Иконка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
                "ordering": ["base_price"],
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="review",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="review",
            name="order",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="review",
            name="driver",
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["-rating"],
                "verbose_name": "Водитель",
                "verbose_name_plural": "Водители",
            },
        ),
        migrations.RemoveField(
            model_name="driver",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="photo",
        ),
        migrations.AddField(
            model_name="driver",
            name="has_cargo_space",
            field=models.BooleanField(default=False, verbose_name="Большой багажник"),
        ),
        migrations.AddField(
            model_name="driver",
            name="has_child_seat",
            field=models.BooleanField(
                default=False, verbose_name="Есть детское кресло"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="max_passengers",
            field=models.IntegerField(default=4, verbose_name="Макс. пассажиров"),
        ),
        migrations.AddField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "🟢 Свободен"),
                    ("busy", "🔴 Занят"),
                    ("offline", "⚫ Не в сети"),
                ],
                default="available",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="car_number",
            field=models.CharField(max_length=15, verbose_name="Номер авто"),
        ),
        migrations.AddField(
            model_name="driver",
            name="available_tariffs",
            field=models.ManyToManyField(
                blank=True, to="B0J_app.tariff", verbose_name="Доступные тарифы"
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
