# Generated by Django 5.2.9 on 2025-12-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "B0J_app",
            "0003_tariff_remove_order_customer_remove_review_customer_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("cash", "💵 Наличные"),
                            ("card", "💳 Банковская карта"),
                            ("apple_pay", "\uf8ff Apple Pay"),
                            ("google_pay", "📱 Google Pay"),
                            ("sberbank", "🐷 Сбербанк Онлайн"),
                            ("tinkoff", "💙 Тинькофф"),
                            ("yoomoney", "💰 ЮMoney"),
                            ("sbp", "🏦 СБП (Система быстрых платежей)"),
                            ("corporate", "🏢 Корпоративный счет"),
                        ],
                        max_length=20,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("icon", models.CharField(max_length=20, verbose_name="Иконка")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Комиссия (%)",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Минимальная сумма",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=100000.0,
                        max_digits=10,
                        verbose_name="Максимальная сумма",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
            ],
            options={
                "verbose_name": "Способ оплаты",
                "verbose_name_plural": "Способы оплаты",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Имя клиента"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Телефон клиента"),
                ),
                ("pickup_address", models.TextField(verbose_name="Адрес подачи")),
                (
                    "destination_address",
                    models.TextField(verbose_name="Адрес назначения"),
                ),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Расстояние (км)",
                    ),
                ),
                (
                    "estimated_time",
                    models.IntegerField(
                        default=0, verbose_name="Примерное время (мин)"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Итоговая цена (₽)",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачен")),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ Ожидание"),
                            ("accepted", "✅ Принят"),
                            ("in_progress", "🚗 В пути"),
                            ("completed", "🏁 Завершен"),
                            ("cancelled", "❌ Отменен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="B0J_app.driver",
                        verbose_name="Водитель",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="B0J_app.tariff",
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to="B0J_app.paymentmethod",
                        verbose_name="Способ оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
    ]
